In [1]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2CAD-ECB0

 C:\Users\SONG\multi_campus\Practice 디렉터리

2021-02-22  오후 05:37    <DIR>          .
2021-02-22  오후 05:37    <DIR>          ..
2021-02-22  오후 05:37    <DIR>          .ipynb_checkpoints
2021-01-13  오후 09:55            59,740 21.01.12_연습.ipynb
2021-01-13  오후 10:44            63,321 21.01.13_연습.ipynb
2021-01-14  오후 10:12            88,735 21.01.14_연습.ipynb
2021-01-15  오후 06:47           121,511 21.01.15_연습.ipynb
2021-01-16  오후 11:19           149,777 21.01.16_연습.ipynb
2021-01-17  오후 10:46           235,575 21.01.17_연습.ipynb
2021-01-18  오후 09:48           236,969 21.01.18_연습.ipynb
2021-01-19  오후 11:19           240,461 21.01.19_연습.ipynb
2021-02-01  오후 10:05           258,204 21.01.23_연습.ipynb
2021-01-26  오후 11:36            39,655 21.01.26_연습.ipynb
2021-01-27  오후 11:42            27,353 21.01.27_연습.ipynb
2021-01-28  오후 11:21            23,092 21.01.28_연습.ipynb
2021-01-29  오후 04:03             1,869 21.01.29_연습.ipynb
2021-02-02  오후 06:31         

In [2]:
import numpy as np

In [3]:
a0 = np.array(9)

In [4]:
print(a0)

9


In [5]:
a0

array(9)

In [6]:
a1 = np.array([1,3,5,7,9])

In [7]:
a1

array([1, 3, 5, 7, 9])

In [9]:
a2 = np.array([[1,3,5],
             [2,4,6],
             [7,9,11],
             [8,10,12]])

In [10]:
a2

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [12]:
a3 = np.array([[[1,2],
               [3,4]],
              [[5,6],
              [7,8]],
              [[9,10],
              [11,12]]])

In [13]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [57]:
a4 = np.array([[[1,2],
               [3,4]],
              [[5,6],
              [7,8]],
              [[9,10],
              [11,12]],
              [[13,14],
              [15,16]]])

In [15]:
print(a4)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [16]:
AR = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [17]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
AR.shape

(12,)

In [19]:
AR2 = AR.reshape(3,2,2)

In [20]:
print(AR2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [21]:
AR3 = AR.reshape(4,3)

In [22]:
print(AR3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
AR3.shape

(4, 3)

In [24]:
AR2.shape

(3, 2, 2)

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a= np.arange(1,135,5)

In [50]:
len(a)

27

In [51]:
a.reshape(3,3,3)

array([[[  1,   6,  11],
        [ 16,  21,  26],
        [ 31,  36,  41]],

       [[ 46,  51,  56],
        [ 61,  66,  71],
        [ 76,  81,  86]],

       [[ 91,  96, 101],
        [106, 111, 116],
        [121, 126, 131]]])

In [52]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
np.random.rand(3,4)

array([[0.0367267 , 0.34108155, 0.06560283, 0.11824251],
       [0.12774202, 0.75510276, 0.23269252, 0.96070451],
       [0.50437218, 0.42939736, 0.09576669, 0.65202535]])

In [64]:
np.random.rand(3,3,3)

array([[[0.0439153 , 0.24874515, 0.67208353],
        [0.44262032, 0.80454234, 0.51089916],
        [0.3587206 , 0.98001175, 0.21277629]],

       [[0.47011229, 0.14287839, 0.5632126 ],
        [0.95949808, 0.92646261, 0.33348802],
        [0.85560217, 0.40627578, 0.76926606]],

       [[0.38433332, 0.21550068, 0.04234217],
        [0.27236447, 0.2805251 , 0.03596173],
        [0.30297877, 0.98327456, 0.12307102]]])

In [66]:
np.random.randint(1,46, size=(5,6))

array([[41, 41, 34,  5, 29, 21],
       [ 4, 29, 45, 19, 42, 16],
       [14, 43, 37, 44, 39, 29],
       [41, 35,  2, 45, 45, 37],
       [40, 17, 33,  2,  8, 38]])

In [67]:
np.random.choice(np.arange(1,46), size=(5,6), replace=False)

array([[ 1, 38, 43, 17, 14, 45],
       [24, 35,  2, 32,  3, 12],
       [21, 25, 16, 30, 39, 11],
       [44, 42,  7, 18, 37, 22],
       [ 8, 13,  9, 27, 29, 31]])

In [69]:
np.random.seed(2045)

In [70]:
np.random.choice(np.arange(1,46),size=(5,6), replace=False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

In [71]:
a1 = np.array([1,3,5,7,9])

In [73]:
a2=np.array([10,30,50,70,90])

In [74]:
a1 + a2

array([11, 33, 55, 77, 99])

In [75]:
a1 - a2

array([ -9, -27, -45, -63, -81])

In [76]:
a1 * a2

array([ 10,  90, 250, 490, 810])

In [77]:
a1 / a2

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [78]:
a1 * 3

array([ 3,  9, 15, 21, 27])

In [79]:
a1 ** 2

array([ 1,  9, 25, 49, 81], dtype=int32)

In [80]:
a1.sum()

25

In [81]:
a2.mean()

50.0

In [82]:
a2.var()

800.0

In [83]:
a2.std()

28.284271247461902

In [84]:
a1.min()

1

In [85]:
a2.max()

90

In [86]:
a1.cumsum()

array([ 1,  4,  9, 16, 25], dtype=int32)

In [87]:
a1.cumprod()

array([  1,   3,  15, 105, 945], dtype=int32)

In [88]:
A1 = np.array([2,4,6,8]).reshape(2,2)

In [89]:
print(A1)

[[2 4]
 [6 8]]


In [90]:
A2 = np.array([3,5,7,9]).reshape(2,2)

In [91]:
print(A2)

[[3 5]
 [7 9]]


In [92]:
A1 @ A2

array([[ 34,  46],
       [ 74, 102]])

In [93]:
A1.dot(A2)

array([[ 34,  46],
       [ 74, 102]])

In [94]:
np.dot(A1, A2)

array([[ 34,  46],
       [ 74, 102]])

In [95]:
np.dot(A2, A1)

array([[ 36,  52],
       [ 68, 100]])

In [96]:
A1 * A2

array([[ 6, 20],
       [42, 72]])

In [98]:
np.transpose(A1)

array([[2, 6],
       [4, 8]])

In [99]:
np.transpose(A2)

array([[3, 7],
       [5, 9]])

In [100]:
!ls -l

'ls'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [101]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2CAD-ECB0

 C:\Users\SONG\multi_campus\Practice 디렉터리

2021-02-22  오후 06:11    <DIR>          .
2021-02-22  오후 06:11    <DIR>          ..
2021-02-22  오후 05:37    <DIR>          .ipynb_checkpoints
2021-01-13  오후 09:55            59,740 21.01.12_연습.ipynb
2021-01-13  오후 10:44            63,321 21.01.13_연습.ipynb
2021-01-14  오후 10:12            88,735 21.01.14_연습.ipynb
2021-01-15  오후 06:47           121,511 21.01.15_연습.ipynb
2021-01-16  오후 11:19           149,777 21.01.16_연습.ipynb
2021-01-17  오후 10:46           235,575 21.01.17_연습.ipynb
2021-01-18  오후 09:48           236,969 21.01.18_연습.ipynb
2021-01-19  오후 11:19           240,461 21.01.19_연습.ipynb
2021-02-01  오후 10:05           258,204 21.01.23_연습.ipynb
2021-01-26  오후 11:36            39,655 21.01.26_연습.ipynb
2021-01-27  오후 11:42            27,353 21.01.27_연습.ipynb
2021-01-28  오후 11:21            23,092 21.01.28_연습.ipynb
2021-01-29  오후 04:03             1,869 21.01.29_연습.ipynb
2021-02-02  오후 06:31         

In [108]:
import pandas as pd

In [118]:
DF1 = pd.read_csv('PII.csv')

In [119]:
DF1

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [116]:
DF2 = pd.read_excel('PII.xlsx')

In [120]:
DF2

Name Gender  Age  Grade Picture BloodType  Height  Weight
0   송태섭     남자   21      3       무         B   179.1    63.9
1   최유정     여자   23      1       유         A   177.1    54.9
2   이한나     여자   20      1       무         A   167.9    50.2
3   김소혜     여자   23      3       무         O   176.1    53.5
4   서태웅     남자   24      4       무         B   176.1    79.8
5   정대만     남자   24      2       유         B   175.2    61.7
6   이정환     남자   22      4       무         B   169.1    69.8
7   채소연     여자   22      2       유        AB   169.9    52.7
8   강백호     남자   23      3       무         O   165.5    68.5
9   전소미     여자   22      2       유         O   161.9    52.3
10  변덕규     남자   21      1       무         A   163.2    55.5
11  정채연     여자   22      2       무         B   157.8    44.9
12  권준호     남자   24      4       유         O   166.9    61.7
13  채치수     남자   23      3       무        AB   181.8    85.9
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [121]:
type(DF1)

pandas.core.frame.DataFrame

In [122]:
type(DF2)

pandas.core.frame.DataFrame

In [123]:
DF1.index

RangeIndex(start=0, stop=17, step=1)

In [124]:
DF1.columns

Index(['Name', 'Gender', 'Age', 'Grade', 'Picture', 'BloodType', 'Height',
       'Weight'],
      dtype='object')

In [125]:
DF1.values

array([['송태섭', '남자', 21, 3, '무', 'B', 179.1, 63.9],
       ['최유정', '여자', 23, 1, '유', 'A', 177.1, 54.9],
       ['이한나', '여자', 20, 1, '무', 'A', 167.9, 50.2],
       ['김소혜', '여자', 23, 3, '무', 'O', 176.1, 53.5],
       ['서태웅', '남자', 24, 4, '무', 'B', 176.1, 79.8],
       ['정대만', '남자', 24, 2, '유', 'B', 175.2, 61.7],
       ['이정환', '남자', 22, 4, '무', 'B', 169.1, 69.8],
       ['채소연', '여자', 22, 2, '유', 'AB', 169.9, 52.7],
       ['강백호', '남자', 23, 3, '무', 'O', 165.5, 68.5],
       ['전소미', '여자', 22, 2, '유', 'O', 161.9, 52.3],
       ['변덕규', '남자', 21, 1, '무', 'A', 163.2, 55.5],
       ['정채연', '여자', 22, 2, '무', 'B', 157.8, 44.9],
       ['권준호', '남자', 24, 4, '유', 'O', 166.9, 61.7],
       ['채치수', '남자', 23, 3, '무', 'AB', 181.8, 85.9],
       ['윤대협', '남자', 22, 2, '유', 'AB', 180.3, 76.2],
       ['김세정', '여자', 21, 1, '무', 'O', 155.5, 44.9],
       ['신준섭', '남자', 23, 1, '무', 'A', 168.9, 62.7]], dtype=object)

In [126]:
DF1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Name       17 non-null     object 
 1   Gender     17 non-null     object 
 2   Age        17 non-null     int64  
 3   Grade      17 non-null     int64  
 4   Picture    17 non-null     object 
 5   BloodType  17 non-null     object 
 6   Height     17 non-null     float64
 7   Weight     17 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 1.2+ KB


In [127]:
DF1.head()

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [128]:
DF1[:5]

Name Gender  Age  Grade Picture BloodType  Height  Weight
0  송태섭     남자   21      3       무         B   179.1    63.9
1  최유정     여자   23      1       유         A   177.1    54.9
2  이한나     여자   20      1       무         A   167.9    50.2
3  김소혜     여자   23      3       무         O   176.1    53.5
4  서태웅     남자   24      4       무         B   176.1    79.8

In [130]:
DF1.tail(3)

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [131]:
DF1[-3:]

Name Gender  Age  Grade Picture BloodType  Height  Weight
14  윤대협     남자   22      2       유        AB   180.3    76.2
15  김세정     여자   21      1       무         O   155.5    44.9
16  신준섭     남자   23      1       무         A   168.9    62.7

In [132]:
DF1.describe()

Age      Grade      Height     Weight
count  17.000000  17.000000   17.000000  17.000000
mean   22.352941   2.294118  170.135294  61.123529
std     1.169464   1.104802    7.853896  11.867894
min    20.000000   1.000000  155.500000  44.900000
25%    22.000000   1.000000  165.500000  52.700000
50%    22.000000   2.000000  169.100000  61.700000
75%    23.000000   3.000000  176.100000  68.500000
max    24.000000   4.000000  181.800000  85.900000

In [133]:
DF1.mean()

Age        22.352941
Grade       2.294118
Height    170.135294
Weight     61.123529
dtype: float64

In [134]:
type(DF1['Height'])

pandas.core.series.Series

In [135]:
DF1['Height']

0     179.1
1     177.1
2     167.9
3     176.1
4     176.1
5     175.2
6     169.1
7     169.9
8     165.5
9     161.9
10    163.2
11    157.8
12    166.9
13    181.8
14    180.3
15    155.5
16    168.9
Name: Height, dtype: float64

In [136]:
DF1[['Height','Age']]

Height  Age
0    179.1   21
1    177.1   23
2    167.9   20
3    176.1   23
4    176.1   24
5    175.2   24
6    169.1   22
7    169.9   22
8    165.5   23
9    161.9   22
10   163.2   21
11   157.8   22
12   166.9   24
13   181.8   23
14   180.3   22
15   155.5   21
16   168.9   23

In [137]:
DF1.Height

0     179.1
1     177.1
2     167.9
3     176.1
4     176.1
5     175.2
6     169.1
7     169.9
8     165.5
9     161.9
10    163.2
11    157.8
12    166.9
13    181.8
14    180.3
15    155.5
16    168.9
Name: Height, dtype: float64

In [139]:
DF1['Height'].mean()

170.1352941176471

In [140]:
DF1['Height'].var()

61.683676470588225

In [141]:
DF1['Height'].min()

155.5

In [142]:
DF1['Age'].max()

24

In [143]:
DF1.groupby(['BloodType']).mean()

Age     Grade      Height  Weight
BloodType                                         
A          21.750000  1.000000  169.275000  55.825
AB         22.333333  2.333333  177.333333  71.600
B          22.600000  3.000000  171.460000  64.020
O          22.600000  2.600000  165.180000  56.180

In [145]:
DF1.groupby(['BloodType'])['Height'].mean()

BloodType
A     169.275000
AB    177.333333
B     171.460000
O     165.180000
Name: Height, dtype: float64

In [146]:
DF1.Height[16]

168.9

In [147]:
DF1.Height[0:5]

0    179.1
1    177.1
2    167.9
3    176.1
4    176.1
Name: Height, dtype: float64

In [148]:
DF1(['Height'])[0]

TypeError: 'DataFrame' object is not callable