# I. 수치미분(Numerical Derivative)
## 1) Import numpy

In [1]:
import numpy as pd

## 2) gradient() 함수 정의
* 다변수 함수의 수치미분

In [12]:
def gradient(machine, param):

  if param.ndim == 1: # 첫번째 파라메터 식
    temp_param = param
    delta = 0.00005
    learned_param = np.zeros(param.shape)

    for index in range(len(param)):
      target_param = float(temp_param[index])
      temp_param[index] = target_param + delta # delta(이동값)를 더하기도 하고 빼기도 하는데 = 중앙미분(차분)
      param_plus_delta = machine(temp_param)
      temp_param[index] = target_param - delta
      param_minus_delta = machine(temp_param)
      learned_param[index] = (param_plus_delta - param_minus_delta) / (2*delta) # 델타 x의 중앙미분을 해서 좌우로 델타거리가 2개가 생겼으니까, 2개를 곱     param_plus_delta = machine(temp_param)
      temp_param[index] = target_param

    return learned_param

  elif param.ndim == 2:
    temp_param = param
    delta = 0.00005
    learned_param = np.zeros(param.shape)

    rows= param.shape[0]
    columns = param.shape[1]

    for row in range(rows):
      for column in range(columns):
        target_param = float(temp_param[row, column])
        temp_param[row, column] = target_param + delta     # delta(이동값)를 더하기도 하고 빼기도 하는데 = 중앙미분(차분)
        param_plus_delta = machine(temp_param)
        temp_param[row, column] = target_param - delta
        param_minus_delta = machine(temp_param)
        learned_param[row, column] = (param_plus_delta - param_minus_delta) / (2*delta) # 델타 x의 중앙미분을 해서 좌우로 델타거리가 2개가 생겼으니까, 2개를 곱     param_plus_delta = machine(temp_param)
        temp_param[row, column] = target_param

    return learned_param
                               

# II. Logic Gate() = 'AND, 'OR', 'NAND'
## 1) sigmoid() 함수 정의

In [3]:
import numpy as np

def sigmoid(x):
  y_hat = 1 / ( 1+ np.exp(-x))
  return y_hat

## 2) LogicGate 클래스 선언

In [22]:
class LogicGate:

  def __init__(self, gate_Type, X_input, y_output):

    # gate_Type 문자열 지정 Member
    self.Type = gate_Type

    # X_input, y_output Member 초기화
    self.X_input = X_input.reshape(4,2)    # (4행 2열) - X가 두개(column)니까,
    self.y_output = y_output.reshape(4,1 )

    # W, b Member 초기화
    self.W = np.random.rand(2,1) # w = x가 2개니까 w도 2개
    self.b = np.random.rand(1)

    # learning_rate Mamber 지정
    self.learning_rate = 0.01

  # Cost_Function(CEE) Method
  def cost_func(self):
    z = np.dot(self.X_input, self.W) + self.b
    y_hat = sigmoid(z)
    delta = 0.00001
    return -np.sum(self.y_output * np.log(y_hat + delta) + (1-self.y_output)*np.log((1-y_hat)+delta)) # Cross Entropy 식
  
  # Learning Method
  def learn(self):
    machine = lambda x : self.cost_func()
    print('Inital Cost = ', self.cost_func())

    for step in range(10001):
      self.W = self.W - self.learning_rate * gradient(machine, self.W)
      self.b =self.b - self.learning_rate * gradient(machine, self.b)

      if (step % 1000 == 0) :
        print('Step = ', step, 'Cost = ', self.cost_func() )

  # Predict Method
  def predict(self, input_data):

    z = np.dot(input_data, self.W)  + self.b
    y_prob = sigmoid(z)

    if y_prob > 0.5:
      result = 1
    else:
      result = 0

    return y_prob, result

## 3) AND_Gate
* X_input, y_output 지정

In [5]:
X_input = np.array([[0,0], [0,1], [1,0],[1,1]])
y_output = np.array([0,0,0,1])

* AND_Gate 객체 생성 및 학습

In [24]:
AND_Gate = LogicGate('AND_GATE', X_input, y_output)
AND_Gate.learn()

Inital Cost =  3.6735015367009556
Step =  0 Cost =  3.636041203894603
Step =  1000 Cost =  1.0140047169910198
Step =  2000 Cost =  0.6628984042552841
Step =  3000 Cost =  0.4928593300852373
Step =  4000 Cost =  0.39118345790307074
Step =  5000 Cost =  0.3235255602584002
Step =  6000 Cost =  0.2753472346781095
Step =  7000 Cost =  0.23936142221150825
Step =  8000 Cost =  0.21150284087773402
Step =  9000 Cost =  0.1893249385394955
Step =  10000 Cost =  0.1712684921620484


* AND_Gate 테스트

In [25]:
print(AND_Gate.Type, '\n')

test_data = np.array([[0, 0],[0,1],[1,0],[1,1]])

for input_data in test_data:
  (sigmoid_val, logical_val) = AND_Gate.predict(input_data)
  print(input_data, '=', logical_val)

AND_GATE 

[0 0] = 0
[0 1] = 0
[1 0] = 0
[1 1] = 1


## 4) OR_Gate
* X_input, y_output

In [27]:
X_input = np.array([[0,0], [0,1], [1,0],[1,1]])
y_output = np.array([0,1,1,1])

* OR_Gate 객체 생성 및 학습

In [28]:
OR_Gate = LogicGate('OR_GATE', X_input, y_output)
OR_Gate.learn()

Inital Cost =  2.2326822376906326
Step =  0 Cost =  2.2246611811396377
Step =  1000 Cost =  0.7640428327569517
Step =  2000 Cost =  0.44859488874644227
Step =  3000 Cost =  0.31233147535184996
Step =  4000 Cost =  0.23775269161803433
Step =  5000 Cost =  0.19116735485873812
Step =  6000 Cost =  0.15948256572342295
Step =  7000 Cost =  0.13661285527851277
Step =  8000 Cost =  0.11936675508090068
Step =  9000 Cost =  0.10591728551139663
Step =  10000 Cost =  0.09514650785143353


* OR_Gate 테스트

In [29]:
print(OR_Gate.Type, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
  (sigmoid_val, logical_val) = OR_Gate.predict(input_data)
  print(input_data, '=', logical_val)

OR_GATE 

[0 0] = 0
[0 1] = 1
[1 0] = 1
[1 1] = 1


## 5) NAND_Gate
* X_input, y_output

In [30]:
X_input = np.array([[0,0], [0,1], [1,0],[1,1]])
y_output = np.array([1,1,1,0])

* NAND_Gate 객체 생성 및 학습

In [31]:
NAND_Gate = LogicGate('NAND_GATE', X_input, y_output)
NAND_Gate.learn()

Inital Cost =  2.8205794786359037
Step =  0 Cost =  2.8132090136410417
Step =  1000 Cost =  1.047182689412004
Step =  2000 Cost =  0.6767136985424577
Step =  3000 Cost =  0.5005421799719807
Step =  4000 Cost =  0.39607877331482577
Step =  5000 Cost =  0.32691014762750803
Step =  6000 Cost =  0.2778212716618471
Step =  7000 Cost =  0.24124520503745142
Step =  8000 Cost =  0.21298287879102065
Step =  9000 Cost =  0.19051708113318302
Step =  10000 Cost =  0.17224840297278496


* NAND_Gate 테스트

In [32]:
print(NAND_Gate.Type, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
  (sigmoid_val, logical_val) = NAND_Gate.predict(input_data)
  print(input_data, '=', logical_val)

NAND_GATE 

[0 0] = 1
[0 1] = 1
[1 0] = 1
[1 1] = 0


# III. XOR_Gate Issue
## 1) XOR_Gate Failure

In [37]:
X_input = np.array([[0,0], [0,1], [1,0],[1,1]])
y_output = np.array([0,1,1,0])

* XOR_Gate 객체 생성 및 학습

In [38]:
XOR_Gate = LogicGate('XOR_GATE', X_input, y_output)
XOR_Gate.learn()

Inital Cost =  3.8123448492874807
Step =  0 Cost =  3.78795303590408
Step =  1000 Cost =  2.772584385518988
Step =  2000 Cost =  2.7725097521610422
Step =  3000 Cost =  2.77250875227414
Step =  4000 Cost =  2.7725087241911317
Step =  5000 Cost =  2.7725087230883516
Step =  6000 Cost =  2.7725087230418444
Step =  7000 Cost =  2.7725087230398593
Step =  8000 Cost =  2.7725087230397745
Step =  9000 Cost =  2.7725087230397705
Step =  10000 Cost =  2.772508723039771


* XOR_Gate 테스트

In [39]:
print(XOR_Gate.Type, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
  (sigmoid_val, logical_val) = XOR_Gate.predict(input_data)
  print(input_data, '=', logical_val)

XOR_GATE 

[0 0] = 1
[0 1] = 1
[1 0] = 1
[1 1] = 0


## 2) XOR_Gate Succeed
* XOR를 (NAND + OR) 계층 및 AND 계층의 조합으로 연산
* 이전 학습된 Parameter로 XOR 수행

In [46]:
input_data =np.array([[0,0], [0,1], [1,0],[1,1]])

HL1_1 = []  # NAND 출력
HL1_2 = []  # OR 출력

new_input_data = []   # AND 입력
final_output = []     # AND(XOR) 출력

for index in range(len(input_data)):

  HL1_1 = NAND_Gate.predict(input_data[index])   # NAND 출력
  HL1_2 = OR_Gate.predict(input_data[index])     # OR 출력

  new_input_data.append(HL1_1[-1])    # AND 입력
  new_input_data.append(HL1_2[-1])    # AND 입력
  print(HL1_1, '\n', HL1_2, '\n', new_input_data)
  
  (sigmoid_val, logical_val) = AND_Gate.predict(np.array(new_input_data))

  final_output.append(logical_val)   # AND(XOR) 출력
  new_input_data = []                # AND 입력 초기화

(array([0.99980269]), 1) 
 (array([0.05195042]), 0) 
 [1, 0]
(array([0.95089301]), 1) 
 (array([0.97931436]), 1) 
 [1, 1]
(array([0.9508918]), 1) 
 (array([0.97930518]), 1) 
 [1, 1]
(array([0.06889584]), 0) 
 (array([0.99997554]), 1) 
 [0, 1]


In [44]:
print(XOR_Gate.Type, '\n')

for index in range(len(input_data)):
  print(input_data[index], '=',   final_output[index])

XOR_GATE 

[0 0] = 0
[0 1] = 1
[1 0] = 1
[1 1] = 0
