In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/rusita-ai/pyData/master/tmdb_5000_movies.csv'
DF = pd.read_csv(url)

DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [2]:
DF.head(1)

budget  ... vote_count
0  237000000  ...      11800

[1 rows x 20 columns]

In [3]:
DF.isnull().values.any()

True

In [4]:
DF.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [12]:
DF['overview'][:1]

0    In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...
Name: overview, dtype: object

In [18]:
DF_MV = DF[['id','title','genres','vote_average','vote_count','popularity','keywords','overview']]
DF_MV.head(1)

id  ...                                                                                             overview
0  19995  ...  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...

[1 rows x 8 columns]

In [8]:
pd.set_option('max_colwidth', 100)
DF_MV[['genres','keywords']][:1]

genres                                                                                             keywords
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...

In [15]:
print(type(DF_MV['genres']),type(DF_MV[['genres']]))

<class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>


In [19]:
from ast import literal_eval

DF_MV['genres'] = DF_MV['genres'].apply(literal_eval)
DF_MV['keywords'] = DF_MV['keywords'].apply(literal_eval)

DF_MV[['genres','keywords']][:1]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


genres                                                                                             keywords
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {...  [{'id': 1463, 'name': 'culture clash'}, {'id': 2964, 'name': 'future'}, {'id': 3386, 'name': 'sp...

In [20]:
print(type(DF_MV['genres']))

<class 'pandas.core.series.Series'>


In [21]:
DF_MV['genres'] = DF_MV['genres'].apply(lambda x: [y['name'] for y in x])
DF_MV['keywords'] = DF_MV['keywords'].apply(lambda x : [y['name'] for y in x])

DF_MV[['genres','keywords']][:1]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


genres                                                                                             keywords
0  [Action, Adventure, Fantasy, Science Fiction]  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, spa...

In [22]:
DF_so['genres'] = DF['genres'].apply(lambda x: [y['name'] for y in x])
DF_so['keywords'] = DF['keywords'].apply(lambda x : [y['name'] for y in x])

DF_so[['genres','keywords']][:1]

TypeError: ignored

In [28]:
print(type(DF['genres'][0]),type(DF_MV['genres'][0]))

<class 'str'> <class 'list'>


In [23]:
from sklearn.feature_extraction.text import CountVectorizer

DF_MV['genres_literal'] = DF_MV['genres'].apply(lambda x: (' ').join(x))
DF_MV['genres_literal'][:1]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


0    Action Adventure Fantasy Science Fiction
Name: genres_literal, dtype: object

In [26]:
DF_MV['genres'][:1]

0    [Action, Adventure, Fantasy, Science Fiction]
Name: genres, dtype: object

In [27]:
print(type(DF_MV['genres_literal'][0]),type(DF_MV['genres'][0]))

<class 'str'> <class 'list'>


In [31]:
count_vect = CountVectorizer(min_df = 0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(DF_MV['genres_literal'])

genre_mat.shape

(4803, 276)

In [32]:
print(len(DF_MV['genres_literal']))

4803


In [33]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)

genre_sim.shape

(4803, 4803)

In [34]:
genre_sim[:1]

array([[1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
        0.        ]])

In [52]:
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1]

In [53]:
genre_sim_sorted_ind[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]])

In [47]:
def find_sim_movie(df, sorted_ind, title_name, top_n = 10):
  title_movie = df[df['title'] == title_name]
  print('title_movie:',title_movie)

  title_index = title_movie.index.values
  print('title_index:', title_index)

  similar_indexes = sorted_ind[title_index, :(top_n)]
  print('similar_indexes:',similar_indexes)
  
  similar_indexes = similar_indexes.reshape(-1)
  print(similar_indexes)
  return df.iloc[similar_indexes]

In [48]:
DF_MV['title'] == 'The Godfather'

0       False
1       False
2       False
3       False
4       False
        ...  
4798    False
4799    False
4800    False
4801    False
4802    False
Name: title, Length: 4803, dtype: bool

In [46]:
genre_sim_sored_ind[3337]

array([2731, 1243, 3636, ..., 2497, 2496,    0])

In [49]:
similar_movies = find_sim_movie(DF_MV, genre_sim_sored_ind, 'The Godfather', 10)

similar_movies[['title','vote_average']]

title_movie:        id  ... genres_literal
3337  238  ...    Drama Crime

[1 rows x 9 columns]
title_index: [3337]
similar_indexes: [[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]
[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]


title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [57]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
  
  title_movie = df[df['title'] == title_name]

  title_index = title_movie.index.values

  similar_indexes = sorted_ind[title_index, :(top_n)]
  print(similar_indexes)

  similar_indexes = similar_indexes.reshape(-1)

  return df.iloc[similar_indexes]

In [58]:
similar_movies = find_sim_movie(DF_MV, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies[['title', 'vote_average']]

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [59]:
DF_MV[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [60]:
C = DF_MV['vote_average'].mean()
m = DF_MV['vote_count'].quantile(0.6)

print('C:',round(C,3), 'm:',round(m,3))

C: 6.092 m: 370.2


In [61]:
percentile = 0.6

m = DF_MV['vote_count'].quantile(percentile)
C = DF_MV['vote_average'].mean()

def weighted_vote_average(record):
  v = record['vote_count']
  R = record['vote_average']

  return ((v/(v+m)) * R) + ((m/(m+v)) * C)

In [62]:
DF_MV['weighted_vote'] = DF_MV.apply(weighted_vote_average, axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [63]:
DF_MV[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', ascending=False)

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
...                        ...           ...            ...         ...
2122                Epic Movie           3.2       4.737894         326
242             Fantastic Four           4.4       4.636554        2278
3746         The Boy Next Door           4.1       4.629738        1022
210             Batman & Robin           4.2       4.591725        1418
1652      Dragonball Evolution           2.9       4.320022         462

[4803 rows x 4 columns]

In [69]:
def find_sim_movie(df, sorted_ind, title_name, top_n = 10):
  title_movie = df[df['title'] == title_name]

  title_index = title_movie.index.values

  similar_indexes = sorted_ind[title_index, :(top_n*2)]
  similar_indexes = similar_indexes.reshape(-1)

  similar_indexes = similar_indexes[similar_indexes != title_index]

  return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

In [70]:
similar_movies = find_sim_movie(DF_MV, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies[['title', 'vote_average', 'weighted_vote']]

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427