In [1]:
doc_list = ['if you take the blue pill, the story ends' ,
'if you take the red pill, you stay in Wonderland',
'if you take the red pill, I show you how deep the rabbit hole goes']

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_verc_simple = TfidfVectorizer()
feature_vec_simple = tfidf_verc_simple.fit_transform(doc_list)

print(feature_vec_simple)

  (0, 2)	0.41556360057939173
  (0, 13)	0.41556360057939173
  (0, 8)	0.24543855687841593
  (0, 0)	0.41556360057939173
  (0, 15)	0.49087711375683185
  (0, 14)	0.24543855687841593
  (0, 17)	0.24543855687841593
  (0, 6)	0.24543855687841593
  (1, 16)	0.39624495215024286
  (1, 7)	0.39624495215024286
  (1, 12)	0.39624495215024286
  (1, 10)	0.3013544995034864
  (1, 8)	0.2340286519091622
  (1, 15)	0.2340286519091622
  (1, 14)	0.2340286519091622
  (1, 17)	0.4680573038183244
  (1, 6)	0.2340286519091622
  (2, 3)	0.3098560092999078
  (2, 4)	0.3098560092999078
  (2, 9)	0.3098560092999078
  (2, 1)	0.3098560092999078
  (2, 5)	0.3098560092999078
  (2, 11)	0.3098560092999078
  (2, 10)	0.23565348175165166
  (2, 8)	0.1830059506093466
  (2, 15)	0.3660119012186932
  (2, 14)	0.1830059506093466
  (2, 17)	0.3660119012186932
  (2, 6)	0.1830059506093466


In [7]:
feature_vec_dencse = feature_vec_simple.todense()

print(feature_vec_dencse)  # (3문장, 18단어)
print(feature_vec_dencse.shape, type(feature_vec_dencse))

[[0.4155636  0.         0.4155636  0.         0.         0.
  0.24543856 0.         0.24543856 0.         0.         0.
  0.         0.4155636  0.24543856 0.49087711 0.         0.24543856]
 [0.         0.         0.         0.         0.         0.
  0.23402865 0.39624495 0.23402865 0.         0.3013545  0.
  0.39624495 0.         0.23402865 0.23402865 0.39624495 0.4680573 ]
 [0.         0.30985601 0.         0.30985601 0.30985601 0.30985601
  0.18300595 0.         0.18300595 0.30985601 0.23565348 0.30985601
  0.         0.         0.18300595 0.3660119  0.         0.3660119 ]]
(3, 18) <class 'numpy.matrix'>


In [8]:
import numpy as np

vec1 = np.array(feature_vec_dencse[0]).reshape(-1,)
vec2 = np.array(feature_vec_dencse[1]).reshape(-1,)
vec3 = np.array(feature_vec_dencse[2]).reshape(-1,)

print(vec1.shape, vec2.shape, vec3.shape, type(vec1))
print(vec1,'\n', vec2,'\n', vec3)

(18,) (18,) (18,) <class 'numpy.ndarray'>
[0.4155636  0.         0.4155636  0.         0.         0.
 0.24543856 0.         0.24543856 0.         0.         0.
 0.         0.4155636  0.24543856 0.49087711 0.         0.24543856] 
 [0.         0.         0.         0.         0.         0.
 0.23402865 0.39624495 0.23402865 0.         0.3013545  0.
 0.39624495 0.         0.23402865 0.23402865 0.39624495 0.4680573 ] 
 [0.         0.30985601 0.         0.30985601 0.30985601 0.30985601
 0.18300595 0.         0.18300595 0.30985601 0.23565348 0.30985601
 0.         0.         0.18300595 0.3660119  0.         0.3660119 ]


In [9]:
import numpy as np
# 두 벡터의 내적을 총 벡터 크기로 정규화
def cos_similarity(v1, v2):
  dot_product = np.dot(v1,v2)
  l2_norm = (np.sqrt(sum(np.square(v1))) * np.sqrt(sum(np.square(v2))))
  similarity = dot_product / l2_norm

  return similarity

In [10]:
similarity_simple = cos_similarity(vec1, vec2)
print('vec1, vec2 코사인 유사도: {0:.5f}'.format(similarity_simple))

vec1, vec2 코사인 유사도: 0.40208


In [11]:
similarity_simple = cos_similarity(vec1, vec3)
print('vec1, vec3 코사인 유사도: {0:.5f}'.format(similarity_simple))

vec1, vec3 코사인 유사도: 0.40425


In [12]:
similarity_simple = cos_similarity(vec2, vec3)
print('vec2, vec3 코사인 유사도: {0:.5f}'.format(similarity_simple))

vec2, vec3 코사인 유사도: 0.45647


In [13]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(feature_vec_simple[0], feature_vec_simple)

array([[1.        , 0.40207758, 0.40425045]])

In [14]:
cosine_similarity(feature_vec_simple[0], feature_vec_simple[1:])

array([[0.40207758, 0.40425045]])

In [18]:
cosine_similarity(feature_vec_simple, feature_vec_simple)

array([[1.        , 0.40207758, 0.40425045],
       [0.40207758, 1.        , 0.45647296],
       [0.40425045, 0.45647296, 1.        ]])

In [19]:
sent_list = ['I eat an apple' , 'Koo have fruit', 'I sell an apple']

In [20]:
tfidf_vec = TfidfVectorizer()
feature_vec = tfidf_vec.fit_transform(sent_list)

In [21]:
cosine_similarity(feature_vec[0], feature_vec[1]) # 아예 관련이 없다는 값

array([[0.]])

In [22]:
cosine_similarity(feature_vec[0], feature_vec[2])

array([[0.53634991]])

In [23]:
import tensorflow_hub as hub
embed = hub.load('https://tfhub.dev/google/Wiki-words-250/2')

In [27]:
words = ['apple', 'eat', 'fruit', 'have', 'sell']
embeddings = embed(words)

In [28]:
import numpy as np
for i in range(len(words)):
  for j in range(i,len(words)):
    print("(",words[i], ",", words[j],")",np.inner(embeddings[i], embeddings[j]))

( apple , apple ) 1.0
( apple , eat ) 0.48909307
( apple , fruit ) 0.78753763
( apple , have ) 0.13348329
( apple , sell ) 0.106232405
( eat , eat ) 1.0
( eat , fruit ) 0.53294003
( eat , have ) 0.3232242
( eat , sell ) 0.2691978
( fruit , fruit ) 1.0
( fruit , have ) 0.13598028
( fruit , sell ) 0.11212408
( have , have ) 1.0
( have , sell ) 0.21071003
( sell , sell ) 1.0
